using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class LightingPreset
{
    public string name = "Daylight";
    public Color color = Color.white;
    public float intensity = 1f;
    public Color ambient = new Color(0.55f, 0.55f, 0.55f);
    [Tooltip("Multiplier for lamp lights (lights named Lamp*@x placed in Props)")]
    public float lampFactor = 1f;
    [Tooltip("Emission colour of window glass (objects named WindowGlass*); lights named Win*@x follow colour+intensity")]
    public Color window = new Color(1f, 1f, 1f);
    [Tooltip("Outdoor zones: sun elevation (deg above horizon) and compass yaw for this time of day")]
    public float sunElevation = 50f;
    public float sunYaw = -30f;
    [Tooltip("Outdoor zones: ambient multiplier for shade fill")]
    public float outdoorAmbient = 1f;
}

public enum DoorWall { Left, Right, Back, Front }

/// One "environment" for BatchDatasetGenerator. Local origin = centre of the floor,
/// +Z = camera side. Shell (floor/walls/ceiling), lights, SpawnPoint and CameraAnchor
/// are generated by ZoneBuilder from these parameters; furniture goes under "Props".
public class Zone : MonoBehaviour
{
    [Header("Dimensions (metres)")]
    public float width = 5.5f;
    public float depth = 6f;
    public float ceilingHeight = 3.2f;
    [Tooltip("Distance from the back wall to the SpawnPoint")]
    public float spawnBackOffset = 2.6f;

    [Header("Door")]
    public DoorWall doorWall = DoorWall.Left;
    [Tooltip("Position along the door wall from its centre: +Z for Left/Right walls, +X for Back/Front walls")]
    public float doorOffset = -1f;
    public float doorWidth = 1f;
    public float doorHeight = 2.1f;

    [Header("Clearance (relax only for tight zones such as the foyer)")]
    public float clearFront = RigSettings.ClearFront;
    public float clearSide = RigSettings.ClearSide;
    public float clearBack = RigSettings.ClearBack;

    [Header("Look")]
    public Material floorMaterial;
    public Material wallMaterial;
    public Material ceilingMaterial;

    [Header("Outdoor")]
    [Tooltip("Open ground, no walls/ceiling; lit by a Sun directional light that follows the time-of-day presets")]
    public bool outdoor = false;

    [Header("Lighting")]
    public List<LightingPreset> presets = DefaultPresets();

    /// Times of day / lighting conditions the generator can switch between.
    public static List<LightingPreset> DefaultPresets()
    {
        return new List<LightingPreset>
        {
            new LightingPreset { name = "Morning",    color = new Color(0.92f, 0.96f, 1f),   intensity = 0.9f,  ambient = new Color(0.55f, 0.6f, 0.68f),  lampFactor = 0.1f,  window = new Color(0.8f, 0.9f, 1.2f) },
            new LightingPreset { name = "Midday",     color = new Color(1f, 1f, 0.97f),      intensity = 1.15f, ambient = new Color(0.66f, 0.67f, 0.68f), lampFactor = 0.05f, window = new Color(2.2f, 2.2f, 2.1f) },
            new LightingPreset { name = "Daylight",   color = new Color(1f, 0.97f, 0.9f),    intensity = 1f,    ambient = new Color(0.6f, 0.62f, 0.65f),  lampFactor = 0.15f, window = new Color(1.6f, 1.55f, 1.4f) },
            new LightingPreset { name = "Overcast",   color = new Color(0.85f, 0.9f, 0.95f), intensity = 0.8f,  ambient = new Color(0.5f, 0.52f, 0.55f),  lampFactor = 0.4f,  window = new Color(0.9f, 0.95f, 1f) },
            new LightingPreset { name = "Evening",    color = new Color(1f, 0.68f, 0.4f),    intensity = 0.6f,  ambient = new Color(0.25f, 0.2f, 0.2f),   lampFactor = 1f,    window = new Color(1.4f, 0.6f, 0.25f) },
            new LightingPreset { name = "Night",      color = new Color(0.5f, 0.6f, 1f),     intensity = 0.2f,  ambient = new Color(0.05f, 0.06f, 0.1f),  lampFactor = 1.3f,  window = new Color(0.02f, 0.04f, 0.1f) },
            new LightingPreset { name = "Artificial", color = new Color(0.85f, 0.92f, 1f),   intensity = 1.2f,  ambient = new Color(0.4f, 0.4f, 0.45f),  lampFactor = 0.5f,  window = new Color(0.1f, 0.12f, 0.2f) },
        };
    }

    public Transform SpawnPoint => transform.Find("SpawnPoint");
    public Transform CameraAnchor => transform.Find("CameraAnchor");
    public Transform LightsRoot => transform.Find("Lights");

    public void GetCameraPose(out Vector3 pos, out Quaternion rot)
    {
        Transform sp = SpawnPoint;
        RigSettings.CameraPose(sp.position, sp.rotation, out pos, out rot);
    }

    public void SetLightsActive(bool on)
    {
        if (LightsRoot != null) LightsRoot.gameObject.SetActive(on);
        foreach (Light l in LampLights()) l.enabled = on;
    }

    /// Prop lights live under Props (so they move with the prop): "Lamp*@x" follow lampFactor,
    /// "Win*@x" (window light) follow the preset colour and intensity.
    IEnumerable<Light> LampLights()
    {
        Transform props = transform.Find("Props");
        if (props == null) yield break;
        foreach (Light l in props.GetComponentsInChildren<Light>(true))
            if (l.name.StartsWith("Lamp") || l.name.StartsWith("Win")) yield return l;
    }

    /// Per-light base intensity lives in each Light's Zone-multiplier: we store it as the
    /// light's initial intensity in a "Lights" child name suffix-free way by scaling from 1.
    public void ApplyPreset(int index)
    {
        if (LightsRoot == null || index < 0 || index >= presets.Count) return;
        LightingPreset p = presets[index];
        foreach (Light l in LightsRoot.GetComponentsInChildren<Light>(true))
        {
            l.color = p.color;
            l.intensity = p.intensity * BaseIntensity(l);
            if (l.type == LightType.Directional)
                l.transform.rotation = transform.rotation * Quaternion.Euler(p.sunElevation, p.sunYaw, 0f);
        }
        foreach (Light l in LampLights())
        {
            if (l.name.StartsWith("Win")) { l.color = p.color; l.intensity = p.intensity * BaseIntensity(l); }
            else l.intensity = p.lampFactor * BaseIntensity(l);
        }
        var mpb = new MaterialPropertyBlock();
        foreach (Renderer r in GetComponentsInChildren<Renderer>(true))
        {
            if (!r.name.StartsWith("WindowGlass")) continue;
            r.GetPropertyBlock(mpb);
            mpb.SetColor("_EmissionColor", p.window);
            r.SetPropertyBlock(mpb);
        }
        RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
        RenderSettings.ambientLight = outdoor ? p.ambient * p.outdoorAmbient : p.ambient;
    }

    /// Sun angles per default preset (used by outdoor zones); called after DefaultPresets().
    public static void SetSunAngles(List<LightingPreset> ps)
    {
        // Morning, Midday, Daylight, Overcast, Evening, Night, Artificial
        float[] el = { 22f, 78f, 52f, 60f, 8f, 25f, 55f };
        float[] yaw = { -50f, 10f, -30f, 0f, 60f, 20f, -30f };
        for (int i = 0; i < ps.Count && i < el.Length; i++) { ps[i].sunElevation = el[i]; ps[i].sunYaw = yaw[i]; }
    }

    // Lights are named "<label>@<baseIntensity>" by ZoneBuilder.
    static float BaseIntensity(Light l)
    {
        int at = l.name.LastIndexOf('@');
        float v;
        if (at >= 0 && float.TryParse(l.name.Substring(at + 1), System.Globalization.NumberStyles.Float,
            System.Globalization.CultureInfo.InvariantCulture, out v)) return v;
        return l.intensity;
    }

    /// Fills `issues` with any rule violations. Empty list = zone is valid.
    public void Validate(List<string> issues)
    {
        issues.Clear();
        Transform sp = SpawnPoint;
        if (sp == null) { issues.Add("No SpawnPoint (rebuild shell)."); return; }
        if (ceilingHeight < RigSettings.MinCeiling)
            issues.Add($"Ceiling {ceilingHeight:F2} m is below the minimum {RigSettings.MinCeiling:F2} m.");
        if (clearFront < RigSettings.ClearFront || clearSide < RigSettings.ClearSide || clearBack < RigSettings.ClearBack)
            Debug.LogWarning($"[Zone] '{name}' uses relaxed clearance (front {clearFront}, side {clearSide}, back {clearBack}).");

        Physics.SyncTransforms();

        // Person volume in the SpawnPoint's frame.
        float y0 = 0.1f, y1 = RigSettings.PersonHeight;
        Vector3 centre = sp.TransformPoint(new Vector3(0f, (y0 + y1) / 2f, (clearFront - clearBack) / 2f));
        Vector3 half = new Vector3(clearSide, (y1 - y0) / 2f, (clearFront + clearBack) / 2f);
        foreach (Collider c in Physics.OverlapBox(centre, half, sp.rotation, ~0, QueryTriggerInteraction.Ignore))
            if (Relevant(c)) issues.Add($"Clearance: '{Path(c.transform)}' intrudes into the person volume.");

        // Camera.
        Vector3 camPos; Quaternion camRot;
        GetCameraPose(out camPos, out camRot);
        foreach (Collider c in Physics.OverlapSphere(camPos, RigSettings.CameraRadius, ~0, QueryTriggerInteraction.Ignore))
            if (Relevant(c)) issues.Add($"Camera: '{Path(c.transform)}' overlaps the camera position.");
        if (camPos.y > transform.position.y + ceilingHeight - 0.3f)
            issues.Add("Camera is within 0.3 m of the ceiling.");

        Transform anchor = CameraAnchor;
        if (anchor != null && (anchor.position - camPos).sqrMagnitude > 0.0001f)
            issues.Add("CameraAnchor does not match RigSettings (rebuild shell).");
    }


    /// Side-band coverage for the dataset camera (see docs/environment-build.md, layout rules).
    /// Steps along the prime band (spawn-1.5 .. spawn+0.8) on each side wall and reports how much of it holds
    /// furniture (colliders under Props, 0.1-1.2 m high) and the largest empty gap. Rugs (no collider) and doorways count as empty.
    public string Coverage()
    {
        Transform sp = SpawnPoint, props = transform.Find("Props");
        if (sp == null || props == null) return "no spawn/props";
        Physics.SyncTransforms();
        float z0 = sp.localPosition.z - 1.5f, z1 = sp.localPosition.z + 0.8f, step = 0.2f;
        var sbd = new System.Text.StringBuilder();
        foreach (int side in new[] { -1, 1 })
        {
            float inner = clearSide, outer = width / 2f - 0.03f;
            float cx = side * (inner + outer) / 2f, hx = (outer - inner) / 2f;
            int filled = 0, steps = 0; float gap = 0, maxGap = 0;
            for (float zz = z0 + step / 2f; zz < z1; zz += step)
            {
                steps++;
                Vector3 c = transform.TransformPoint(new Vector3(cx, 0.65f, zz));
                bool hit = false;
                foreach (Collider col in Physics.OverlapBox(c, new Vector3(hx, 0.55f, step / 2f), transform.rotation, ~0, QueryTriggerInteraction.Ignore))
                    if (col.transform.IsChildOf(props)) { hit = true; break; }
                if (hit) { filled++; gap = 0; } else { gap += step; if (gap > maxGap) maxGap = gap; }
            }
            sbd.Append((side < 0 ? "image-right(-X)" : "image-left(+X)") + ": " + (100f * filled / steps).ToString("F0") + "% covered, largest gap " + maxGap.ToString("F1") + " m;  ");
        }
        return sbd.ToString();
    }

    bool Relevant(Collider c)
    {
        if (c.transform == transform) return false;
        if (!c.transform.IsChildOf(transform)) return false; // other zones / the character are not ours
        return c.name != "Floor";
    }

    string Path(Transform t)
    {
        string s = t.name;
        while (t.parent != null && t.parent != transform) { t = t.parent; s = t.name + "/" + s; }
        return s;
    }
}
